# Site settings
author: Pan Leung
title: Ideas that tickle and nag
header-img: img/home-bg.png
email: leungpanela@gmail.com
copyright_name: Pan Leung
description: > # this means to ignore newlines until "baseurl:"
  Beginning
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  GenMaker

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
